package com.ensg.spring.hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class EvenementController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private EvenementRepository eventRepository;

    @Autowired
    private ParticipantRepository userRepository;

    @GetMapping(path="/addEvent") // Map ONLY GET Requests
    public @ResponseBody
    String addEvent (@RequestParam String intitule
            , @RequestParam String theme
            , @RequestParam String date_debut
            , @RequestParam String duree
            , @RequestParam String nb_part_max
            , @RequestParam String description
            , @RequestParam String organisateur
            , @RequestParam String type_event) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request


        Evenement event = new Evenement( intitule , theme, date_debut, duree,
                nb_part_max, description, organisateur, type_event);


        event.setIntitule();
        event.setTheme();
        event.setDate_debut();
        event.setDuree();
        event.setNb_part_max();
        event.setDescription();
        event.setOrganisateur();
        event.setType_event();

        eventRepository.save(event);

        return "Saved";


    }


    @GetMapping(path="/allEvent")
    public @ResponseBody Iterable<Evenement> getAllEvents() {
        return eventRepository.findAll();
    }

    @GetMapping(path="/addP/{idP}/{idE}")
    public  @ResponseBody String getPartiEv(@PathVariable int idP,
                                            @PathVariable int idE) {
        Participant parti =  userRepository.findById(idP).get();
        Evenement even =  eventRepository.findById(idE).get();
        even.addP(parti);
        parti.addE(even);
        eventRepository.save(even);
        userRepository.save(parti);

        return "Saved";
    }
    
     public void delete(Evenement event) {
    	eventRepository.delete(event);
    }
    

}
